version: "3"
services:
  event-bus:
    build: ./example/event-bus
    ports:
      - "8081:8081"
    volumes:
      - ./example/event-bus:/code
  create-account:
    build: ./example/create-account
    volumes:
      - ./example/create-account:/code
    depends_on:
      - event-bus
  dispatch-email:
    build: ./example/dispatch-email
    volumes:
      - ./example/dispatch-email:/code
    depends_on:
      - event-bus
  cache:
    image: "redis:alpine"
