version: "3"
services:
  event-source:
    build: ./example/event-bus
    ports:
      - "8081:8080"
    volumes:
      - ./example/event-bus:/code
      - ./packages:/temp/packages
  # client:
  #   build: ./packages/client
  #   ports:
  #     - "8082:8080"
  #   volumes:
  #     - ./packages/client:/code
  # cache:
  #   image: "redis:alpine"
