version: "3"
services:
  event-source:
    build: ./packages/event-bus
    ports:
      - "8081:8080"
    volumes:
      - ./packages/event-bus:/code
  client:
    build: ./packages/client
    ports:
      - "8082:8080"
    volumes:
      - ./packages/client:/code
  cache:
    image: "redis:alpine"
